"""auto update

Revision ID: 10f702a8b44f
Revises: 8e1485ac6b34
Create Date: 2026-09-23 00:25:20.537273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f702a8b44f'
down_revision: Union[str, Sequence[str], None] = '8e1485ac6b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('spec_json', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('plan_json', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('artifact_key', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('test_report_json', sa.String(), nullable=True))
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.drop_column('projects', 'test_report_json')
    op.drop_column('projects', 'artifact_key')
    op.drop_column('projects', 'plan_json')
    op.drop_column('projects', 'spec_json')
    # ### end Alembic commands ###