"""auto update

Revision ID: 7a4e89231834
Revises: d6eb689f4f7c
Create Date: 2026-09-23 18:17:34.727224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4e89231834'
down_revision: Union[str, Sequence[str], None] = 'd6eb689f4f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('assertion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'assertion')
    # ### end Alembic commands ###