"""auto update

Revision ID: 8e1485ac6b34
Revises: 
Create Date: 2026-09-22 23:37:02.050212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1485ac6b34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('run_no', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=True),
    sa.Column('stage_order', sa.Integer(), nullable=True),
    sa.Column('stage_state', sa.String(), nullable=False),
    sa.Column('stage_log', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('output_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_tasks_id'), 'build_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_build_tasks_project_id'), 'build_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_build_tasks_user_id'), 'build_tasks', ['user_id'], unique=False)
    op.create_table('oidc_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('code_verifier', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oidc_states_id'), 'oidc_states', ['id'], unique=False)
    op.create_index(op.f('ix_oidc_states_state'), 'oidc_states', ['state'], unique=True)
    op.create_table('project_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('diff_summary', sa.String(), nullable=True),
    sa.Column('files_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_versions_id'), 'project_versions', ['id'], unique=False)
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_versions_user_id'), 'project_versions', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('template_key', sa.String(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('latest_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('usage_quotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('quota_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_quotas_id'), 'usage_quotas', ['id'], unique=False)
    op.create_index(op.f('ix_usage_quotas_user_id'), 'usage_quotas', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_quotas_user_id'), table_name='usage_quotas')
    op.drop_index(op.f('ix_usage_quotas_id'), table_name='usage_quotas')
    op.drop_table('usage_quotas')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_versions_user_id'), table_name='project_versions')
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_index(op.f('ix_project_versions_id'), table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index(op.f('ix_oidc_states_state'), table_name='oidc_states')
    op.drop_index(op.f('ix_oidc_states_id'), table_name='oidc_states')
    op.drop_table('oidc_states')
    op.drop_index(op.f('ix_build_tasks_user_id'), table_name='build_tasks')
    op.drop_index(op.f('ix_build_tasks_project_id'), table_name='build_tasks')
    op.drop_index(op.f('ix_build_tasks_id'), table_name='build_tasks')
    op.drop_table('build_tasks')
    # ### end Alembic commands ###