"""auto update

Revision ID: 9d6845ad8e0b
Revises: b63343938104
Create Date: 2026-09-23 19:43:10.392758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6845ad8e0b'
down_revision: Union[str, Sequence[str], None] = 'b63343938104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug_fix_logs', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_bug_fix_logs_user_id'), 'bug_fix_logs', ['user_id'], unique=False)
    op.add_column('bugs', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_bugs_user_id'), 'bugs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bugs_user_id'), table_name='bugs')
    op.drop_column('bugs', 'user_id')
    op.drop_index(op.f('ix_bug_fix_logs_user_id'), table_name='bug_fix_logs')
    op.drop_column('bug_fix_logs', 'user_id')
    # ### end Alembic commands ###