"""auto update

Revision ID: b63343938104
Revises: edfc51a7791b
Create Date: 2026-09-23 19:42:20.043709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63343938104'
down_revision: Union[str, Sequence[str], None] = 'edfc51a7791b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_fix_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('source_version', sa.Integer(), nullable=True),
    sa.Column('target_version', sa.Integer(), nullable=True),
    sa.Column('artifact_key', sa.String(), nullable=True),
    sa.Column('changes_json', sa.String(), nullable=True),
    sa.Column('diff_summary', sa.String(), nullable=True),
    sa.Column('retest_json', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_fix_logs_bug_id'), 'bug_fix_logs', ['bug_id'], unique=False)
    op.create_index(op.f('ix_bug_fix_logs_id'), 'bug_fix_logs', ['id'], unique=False)
    op.create_index(op.f('ix_bug_fix_logs_project_id'), 'bug_fix_logs', ['project_id'], unique=False)
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('reproduction', sa.String(), nullable=True),
    sa.Column('related_case_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fix_attempts', sa.Integer(), nullable=True),
    sa.Column('latest_fix_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('target_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bugs_id'), 'bugs', ['id'], unique=False)
    op.create_index(op.f('ix_bugs_latest_fix_id'), 'bugs', ['latest_fix_id'], unique=False)
    op.create_index(op.f('ix_bugs_project_id'), 'bugs', ['project_id'], unique=False)
    op.create_index(op.f('ix_bugs_related_case_id'), 'bugs', ['related_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bugs_related_case_id'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_project_id'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_latest_fix_id'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_id'), table_name='bugs')
    op.drop_table('bugs')
    op.drop_index(op.f('ix_bug_fix_logs_project_id'), table_name='bug_fix_logs')
    op.drop_index(op.f('ix_bug_fix_logs_id'), table_name='bug_fix_logs')
    op.drop_index(op.f('ix_bug_fix_logs_bug_id'), table_name='bug_fix_logs')
    op.drop_table('bug_fix_logs')
    # ### end Alembic commands ###