"""auto update

Revision ID: edfc51a7791b
Revises: 7a4e89231834
Create Date: 2026-09-23 18:20:50.394794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfc51a7791b'
down_revision: Union[str, Sequence[str], None] = '7a4e89231834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_test_cases_user_id'), 'test_cases', ['user_id'], unique=False)
    op.add_column('test_runs', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_test_runs_user_id'), 'test_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_runs_user_id'), table_name='test_runs')
    op.drop_column('test_runs', 'user_id')
    op.drop_index(op.f('ix_test_cases_user_id'), table_name='test_cases')
    op.drop_column('test_cases', 'user_id')
    # ### end Alembic commands ###